### ISSUE TITLE
Question - Update contact fields after successfull DOI (example: optin_status=Bestätigt)

### ISSUE THREAD

**Issue by marc4s** [content-optimizer-gmbh/mautic-doi-plugin#11]
Hi,

I have a question regarding this:
Update contact fields after successfull DOI (example: optin_status=Bestätigt)

 I added the optin_status as custom field as I need this for dynamic content(there are no segments available to choose contacts which are subscribed (or not anymore subscribed).
But how to remove this field if a customer unsubscribed or adjust the field so that I can adjust the dynamic content. otherwise users would see the subscribed content even if they are already unsubscribed. 

Am I right? thanks for information.

kind regards
Marc

**Comment by sebastian-fahrenkrog** [comment]
@marc4s  I would use a campaign or a single form action to update the lead field in case he unsubscribe. 

Greetings
Sebastian
