### ISSUE TITLE
All contacts marked DNC (bounced) instantly -4.4.9

### ISSUE THREAD

**Issue by Robmobius** [content-optimizer-gmbh/mautic-doi-plugin#12]
I installed and configured the plugin in 4.4.9

Server is nginx with php-fpm, php 7.4

![image](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/16938630/0863a659-cf11-4fcc-b5e3-128fae3c3857)

To test I use an incognito browser and submit the opt in form as new contact. The new contact is added to Mautic and instantly marked as "Bounced".

![image](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/16938630/c5202720-fbfb-464e-bf9a-13e21ed71294)

On reviewing the contact timeline no opt in email is ever sent. 

Other actions custom fields configured via the plugin are updated.

I suspect the issue maybe related to the "validate email" option. I have mapped the email field to "validate email" meaning the email field is blank so Mautic does not have an email address to send the DOI email to. I assume the plugin is supposed to handle the use of the temp field "validate email" and use that to send the DOI email? Perhaps this not a bug but a configuration error on my behalf?

PS - I have taken detailed notes for the Joey Keller video and can perhaps assist with documentation/ tut video once I have gotten this working correctly.

**Comment by sebastian-fahrenkrog** [comment]
Ah sorry. I see: i've never used that config field. At the moment the plugin searched for a lead field email_validate if email is empty for the lead. 

Okay, thanks for the bug report! Have to fix it

**Comment by sebastian-fahrenkrog** [comment]
@Robmobius 

The email alias problem should be fixed here: 

https://github.com/content-optimizer-gmbh/mautic-doi-plugin/blob/9f7c2b9403a338222cda0df6caa8134a29037081/src/JotaworksDoiBundle/EventListener/FormSubscriber.php#L232

Could you please check if this file
src/JotaworksDoiBundle/EventListener/FormSubscriber.php

Contains the fix: 

        //if email address is empty we take email_validate as email address  
        if( !$currentLead['email'] && isset($currentLead['email_validate']) && $currentLead['email_validate'] )
        {
            $currentLead['email'] = $currentLead['email_validate'];
        }

**Comment by Robmobius** [comment]
Applied the fix but same behaviour. Replaced the contents of FormSubscriber.php with the new file you supplied. Saved and cleared cache. On testing the email bounces instantly. The email form field in the optin form is mapped to email_validate. Other actions are working though. 

Here is the contact record showing the email validate field is filled.

![Screenshot 2023-06-25 at 14 38 17](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/16938630/930ba11a-c725-4edc-8ce1-44130be3e0df)

here is the timeline
![image](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/16938630/afa4c332-bc2c-4b74-8c70-0121708f710d)

Here is the configuration of the plugin
![image](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/16938630/d9efe915-8494-4bc7-bc25-828636c5d2d7)

**Comment by sebastian-fahrenkrog** [comment]
@Robmobius  Could you please give me a lead screenshot where you show the details of the form submitted entry (just click the icon next to the text, it will reveal the form details submitted) and also do the same with the doi entry above that?

**Comment by IonutOjicaDE** [comment]
I just installed the plugin on my instance 4.4.11 and it works as expected. The contacts are not marked as DNC.
But I found another issue: there are created multiple contacts with the same email address.
