### ISSUE TITLE
Email click no longer recorded in Mautic after installing this plugin

### ISSUE THREAD

**Issue by TechBill** [content-optimizer-gmbh/mautic-doi-plugin#14]
I don't know if it this plugin causing this issue or something else but wanted to start a thread to determine it not the cause of my issue. 

This plugin DOI is working but recently our marketing team just asked me why they no longer could see the click count on each email in email dashboard so I went to investigate it.  

It turn out that almost a month worth of emails sent out no longer record the clicks from content of email and it start happening almost around at the same time I installed this plugin.

I have not yet disable this plugin but I am trying to troubleshoot to determine this plugin is the cause or not.  Could you help me how I would go about to troubleshoot this?

Here a screenshot from one of the email that have a large subscriber and you can see it's all zero's 

![Screenshot 2023-09-27 at 11 23 25 AM](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/945103/bea9296f-7d47-4112-a88b-fb16d9c07d75)

**Comment by sebastian-fahrenkrog** [comment]
Good morning @TechBill ,

The link tracking in Mautic is achieved by rewriting the email links in the email. 
Currently, I'm not aware of any reason how the DOI plugin could disrupt this process.

Therefore, my first step would be to look at a lead who has received an email and view the email there.

All links should start with <mautic-domain>/r/... 

Is that the case?

**Comment by TechBill** [comment]
I have several lead account that receive emails to confirm it was sent successfully each time we send out newsletter or announcement and none of those emails had links that start with your-mautic-domain/r/...   

I went back to previous email about a month ago and all of the link start with your-mautic-domain/r/...  so something broke somewhere but strangely it start around the time I installed your plugin .. maybe it not your plugin but a coindience 

thank you for pointing out that link should start your-mautic-domain/r/...   so now I know where to start troubleshooting.

**Comment by sebastian-fahrenkrog** [comment]
Please check under configuration -> email settings 

if the setting  "Disable trackable urls" is active. 

**This setting should be off**

It could also be a problem with the email template (mautic sometimes does not find the links to rewrite in the email html code if the html is formatted different)

**Comment by TechBill** [comment]
It's off and been that way for almost 2 years now since we start using Mautic

<img width="962" alt="Screenshot 2023-09-28 at 8 33 18 AM" src="https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/945103/f8e8a61f-c9ee-4098-b48f-f0914a13ce6a">

We have not made any changes to the email template. We been using the same email template and I do know that staff has been cloning like previous newsletter email template and just updated text or image then send it out. They been doing this for almost 2 years with no issue. 

It stopped tracking about a month ago but just strange that it happened to be the same time I install the DOI  plugin 

I just create a new email template and sent it out to myself.  No tracking URL appended to the link in the email at all. 

Something in our Mautic broke and we are still trying to figure out what broke,

**Comment by sebastian-fahrenkrog** [comment]
@TechBill Lets see. 

What is your current mautic version? 

Can you provide a screenshot of all the plugins you have active? 

Have you take a look at the mautic log file and look for new lines after sending an email? If there are any new lines can you 
provide them?

**Comment by TechBill** [comment]
We have looked in Mautic file, httpd log, php log and found nothing in there that would be related to this issue. 

It's at version 4.4.10

here are the screenshot of all of our plugin 

<img width="1057" alt="Screenshot 2023-09-28 at 9 19 36 AM" src="https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/945103/27a85479-9f13-4442-ab89-bb5fac117a53">

I am getting ready to zip up your plugin and run a test but one thing that caught my attention is the [JotaworksEmailTrackingBundle] which I don't recall installing so I am looking into that now

**Comment by sebastian-fahrenkrog** [comment]
JotaworksEmailTrackingBundle is a plugin which does exactly this: remove the tracking links from emails. 

https://github.com/content-optimizer-gmbh/mautic-email-tracking

**Comment by TechBill** [comment]
Yeah just tested it before you posted by removing that plugin ... two things that puzzles me 

We don't remember installing that plugin and second it never show up in our Plugin list in configuration that is why we didn't detect it earlier until we saw it now in the plugin folder.  

Was it even part of this plugin?  

We removed that plugin and send out email in our test segment .. all links are being tracked again. 

Thank you but it still puzzling where that plugin came from or we may have been following a DOI instruction somewhere and wound up installing this plugin somehow.

**Comment by sebastian-fahrenkrog** [comment]
@TechBill  I don't think so. The plugin must be downloaded and uploaded from github. If you upload it and don't refresh the plugin list the plugin does not show up in the list. 

So I think no magic is involved here. Somebody uploaded it without thinking what the plugin does. 

I will close this issue here.

**Comment by sebastian-fahrenkrog** [comment]
Closed
