### ISSUE TITLE
Instalation Issue in Mautic 4.4.10

### ISSUE THREAD

**Issue by cryptogabovz** [content-optimizer-gmbh/mautic-doi-plugin#15]
I installed the plugin in the correct folder, cleared the cache, and then went to my Mautic instance, but I couldn't see the installed plugin.

The plugin was placed in the following directory:
/var/www/html/mautic/plugins/JotaworksDoiBundle

I then updated the cache using the command:
php bin/console mautic:plugins:reload

However, I still haven't been able to get the plugin to appear within Mautic.

Mautic V 4.4.10

Screen Cap
![mautic plugins](https://github.com/content-optimizer-gmbh/mautic-doi-plugin/assets/35388977/213dd302-74e3-4746-83a9-643774d06f3f)

**Comment by sebastian-fahrenkrog** [comment]
Hey @cryptogabovz 

We use the plugin in production on multiple 4.4.10 installations. 

Please check your folder permissions and make sure that the plugin folder got the right permissions and the right user. 

Like this: 
cd /var/www/html/mautic/plugins/
find . -type f -exec chmod 644 {} \;
find . -type d -exec chmod 755 {} \;
chown -R www-data:www-data *

( Be carefull I don't know your setup and if your installation is under the user www-data and the group www-data) 

Could you post a screenshot of the directory listing from the /var/www/html/mautic/plugins/JotaworksDoiBundle folder? 

Greetings 
Sebastian
