### ISSUE TITLE
[Bug] lead fields not populated correctly

### ISSUE THREAD

**Issue by putzwasser** [content-optimizer-gmbh/mautic-doi-plugin#7]
The lead fields are not populated correctly.

`tokenid` is gibberish and `doi_ip` is left blank:

See the lead's field values:
![image](https://user-images.githubusercontent.com/26040044/228085543-ae15355f-b7bb-4276-843e-fc973dea925e.png)

![image](https://user-images.githubusercontent.com/26040044/228086081-88bb4c16-be06-4f97-bfc4-1de7094e405d.png)

The form is set up correctly, as far as i could tell

![image](https://user-images.githubusercontent.com/26040044/228086243-a96f474c-c1e8-496a-b2bc-0cc06cc2d312.png)

Custom fields are set up, too

![image](https://user-images.githubusercontent.com/26040044/228086382-e21821fb-9c5b-4fbe-90af-b9397482cc10.png)

**Comment by putzwasser** [comment]
> For me {doi_ip} and {doi_datetime} are properly filled.
How did you configure those two custom fields? Are both strings or other data types? As I said, it's not working for me for some reason.

**Comment by KreativeKrise** [comment]
> although it is called `doi_timestamp` instead of `doi_datetime `

You are absolutely right! I probably still had the data type in mind, while writing the comment :)

> How did you configure the custom field for the IP? Is it a string or some other data type? As I said, it's not working for me for some reason.

The data type of the custom field is `Text`.

**Comment by sebastian-fahrenkrog** [comment]
Hey guys! Thank you for your feedback and help! 

@KreativeKrise  I just merged your pull request. Sorry for beeing late, but I was not getting notifications from github.
