### ISSUE TITLE
Timestring should be a Date(time) object.

### ISSUE THREAD

**Issue by putzwasser** [content-optimizer-gmbh/mautic-doi-plugin#8]
Mautic has a distinct Date/Time data type for custom fields.

![image](https://user-images.githubusercontent.com/26040044/228087123-bb7997f5-6aaf-46e0-b221-9c27c4f617e8.png)

Currently, `$timestring` is a hard coded date time string. 

https://github.com/content-optimizer-gmbh/mautic-doi-plugin/blob/99389574f5d0373e6b3e5a940e252a48e846bdba/src/JotaworksDoiBundle/Helper/LeadHelper.php#L39

It were better if it would use the correct datatype which would allow to format the date/time later on without the need to parse the string first.

**Comment by KreativeKrise** [comment]
The field also seems to be filled correctly if you select "Date/Time" as data type.

**Comment by sebastian-fahrenkrog** [comment]
@putzwasser  I think mautic does nearly the same:

https://github.com/mautic/mautic/blob/07bbe8a2f39ffddb3bb9dceb14bc77ba9dcf80d0/app/bundles/LeadBundle/Helper/CustomFieldHelper.php#L71

I think I  would leave it with that. 

Greetings 
Sebastian
